MCU = RP2040
BOARD = GENERIC_RP_RP2040
BOOTLOADER = rp2040
# ALLOW_WARNINGS = yes
# PICO_INTRINSICS_ENABLED = no

# Build Options
#ENCODER_ENABLE = yes
#OLED_ENABLE = yes
#OLED_DRIVER = ssd1306

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = adns9800
