# MCU name
MCU = RP2040
BOARD = GENERIC_RP_RP2040
BOOTLOADER = rp2040

# Bootloader selection
ALLOW_WARNINGS = yes
PICO_INTRINSICS_ENABLED = no

SLEEP_LED_ENABLE = no
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
WS2812_DRIVER = vendor
SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor
WPM_ENABLE = yes
