MCU = RP2040
BOARD = GENERIC_RP_RP2040
BOOTLOADER = rp2040
ALLOW_WARNINGS = yes
PICO_INTRINSICS_ENABLED = no

# Build Options
AUDIO_ENABLE = yes
AUDIO_DRIVER = pwm_hardware
# OLED_ENABLE = yes
# OLED_DRIVER = SSD1306

QUANTUM_PAINTER_ENABLE   = yes
QUANTUM_PAINTER_DRIVERS += st7789_spi
QUANTUM_PAINTER_LVGL_INTEGRATION = yes