# MCU = RP2040
# BOARD = GENERIC_RP_RP2040
# BOOTLOADER = rp2040
# ALLOW_WARNINGS = yes
# PICO_INTRINSICS_ENABLED = no

# DEFAULT_FOLDER = ergohaven/velvet/rev1

# SPLIT_KEYBOARD = yes
# SERIAL_DRIVER = vendor
